name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Validate project structure
      run: |
        echo "🔍 Validating project structure..."
        find . -name "*.html" -type f | head -5
        find . -name "*.css" -type f | head -5
        find . -name "*.js" -type f | head -5
        echo "✅ Project structure validated"
    
    - name: Deploy via DigitalOcean API
      env:
        DO_TOKEN: ${{ secrets.DO_TOKEN }}
        DROPLET_ID: ${{ secrets.DROPLET_ID }}
      run: |
        echo "🚀 Starting deployment via DigitalOcean API..."
        
        # Install doctl (DigitalOcean CLI)
        wget https://github.com/digitalocean/doctl/releases/download/v1.104.0/doctl-1.104.0-linux-amd64.tar.gz
        tar xf doctl-1.104.0-linux-amd64.tar.gz
        sudo mv doctl /usr/local/bin
        
        # Authenticate with DigitalOcean
        doctl auth init --access-token $DO_TOKEN
        
        # Execute deployment commands on droplet
        doctl compute ssh $DROPLET_ID --ssh-command "cd /var/www/html/edbetosolutions && git fetch origin && git reset --hard origin/main && git pull origin main && chown -R www-data:www-data /var/www/html/edbetosolutions && chmod -R 755 /var/www/html/edbetosolutions && echo 'Deployment completed successfully!'"
        
        echo "✅ Deployment completed via DigitalOcean API!"
        echo "🌐 Site available at: https://edbetosolutions.tech"
